import type { Database } from "../src/integrations/supabase/types";

type SupplierInsert = Database["public"]["Tables"]["suppliers"]["Insert"];
type PoolInsert = Database["public"]["Tables"]["asset_pools"]["Insert"];

export type SupplierKey =
  | "sterlingAndes"
  | "aurumContinental"
  | "lithionPacific"
  | "crystallineQuartz"
  | "polarisNorthern";

export const SUPPLIER_ORDER: SupplierKey[] = [
  "sterlingAndes",
  "aurumContinental",
  "lithionPacific",
  "crystallineQuartz",
  "polarisNorthern",
];

export const DEFAULT_USER_IDS: Record<SupplierKey, string> = {
  sterlingAndes: "112f419a-c406-4262-a278-d194e68e22c5",
  aurumContinental: "9c9d93b3-9684-4e26-8145-47fd59c57443",
  lithionPacific: "1b66c1b0-4170-4ef0-b483-e347d6733120",
  crystallineQuartz: "d01d547b-da21-4f44-9359-981010a5814d",
  polarisNorthern: "84567ea8-fffe-4ba8-913d-832e7b5d1655",
};

type SupplierProfile = Omit<SupplierInsert, "user_id">;

export const SUPPLIERS_DATA: Record<SupplierKey, SupplierProfile> = {
  sterlingAndes: {
    company_name: "Sterling Andes Silver SA",
    fantasy_name: "Sterling Andes",
    email: "trade@sterlingandes.example",
    phone: "+54 11 4000 1100",
    cnpj: null,
    description:
      "Patagonia and Atacama silver miner operating four high-altitude mines. We refine 999 fine silver bars, mint numismatic coins and trade concentrate from our own smelter network. Long-term offtake contracts with industrial buyers across South America and Europe.",
    logo_url:
      "https://images.unsplash.com/photo-1610375461246-83df859d849d?q=80&w=400&auto=format&fit=crop",
    status: "approved",
  },
  aurumContinental: {
    company_name: "Aurum Continental Group Ltd",
    fantasy_name: "Aurum Continental",
    email: "desk@aurumcontinental.example",
    phone: "+233 30 290 4400",
    cnpj: null,
    description:
      "West African gold producer with operations in Ghana, Mali and Burkina Faso. LBMA Good Delivery cast bars, granules and minted coins, all backed by audited chain-of-custody and ESG-compliant artisanal partnerships.",
    logo_url:
      "https://images.unsplash.com/photo-1610375461369-d1859ddd13ad?q=80&w=400&auto=format&fit=crop",
    status: "approved",
  },
  lithionPacific: {
    company_name: "Lithion Pacific Resources Pty",
    fantasy_name: "Lithion Pacific",
    email: "offtake@lithionpacific.example",
    phone: "+61 8 9221 7700",
    cnpj: null,
    description:
      "Australia and Chile lithium platform spanning the Pilbara hard-rock belt and the Salar de Atacama brine fields. We deliver battery-grade carbonate, hydroxide, spodumene concentrate and recycled black-mass derivatives to Tier-1 cell makers.",
    logo_url:
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=400&auto=format&fit=crop",
    status: "approved",
  },
  crystallineQuartz: {
    company_name: "Crystalline Quartz Holdings SA",
    fantasy_name: "Crystalline Quartz",
    email: "sales@crystalline-quartz.example",
    phone: "+55 31 3500 7700",
    cnpj: null,
    description:
      "Brazil and Madagascar high-purity quartz supplier. Vertically integrated from vein-mine to 4N+ HPQ powder for semiconductor and solar customers, with secondary streams in optical crystal, foundry sand and collector specimens.",
    logo_url:
      "https://images.unsplash.com/photo-1518894781321-630e638d0742?q=80&w=400&auto=format&fit=crop",
    status: "approved",
  },
  polarisNorthern: {
    company_name: "Polaris Northern Mining Inc",
    fantasy_name: "Polaris Northern",
    email: "info@polarisnorthern.example",
    phone: "+1 867 555 4040",
    cnpj: null,
    description:
      "Canadian multi-metal junior with placer gold operations in the Yukon, silver-lead concentrate in the Athabasca basin, quartz veins in Manitoba and a pilot lithium brine project in Saskatchewan.",
    logo_url:
      "https://images.unsplash.com/photo-1454942901704-3c44c11b2ad1?q=80&w=400&auto=format&fit=crop",
    status: "approved",
  },
};

type PoolDraft = Omit<PoolInsert, "supplier_id" | "slug"> & {
  /** explicit slug override; otherwise derived from token_symbol */
  slug?: string;
};

const GOLD_THUMB =
  "https://images.unsplash.com/photo-1610375461249-bcfb1c93c2c8?q=80&w=1200&auto=format&fit=crop";
const GOLD_BAR_THUMB =
  "https://images.unsplash.com/photo-1589998059171-988d887df646?q=80&w=1200&auto=format&fit=crop";
const SILVER_THUMB =
  "https://images.unsplash.com/photo-1574607383476-f517f260d30b?q=80&w=1200&auto=format&fit=crop";
const SILVER_COIN_THUMB =
  "https://images.unsplash.com/photo-1605792657660-596af9009e82?q=80&w=1200&auto=format&fit=crop";
const LITHIUM_BRINE_THUMB =
  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop";
const LITHIUM_PLANT_THUMB =
  "https://images.unsplash.com/photo-1581094289810-adf5d25690e3?q=80&w=1200&auto=format&fit=crop";
const QUARTZ_CRYSTAL_THUMB =
  "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop";
const QUARTZ_VEIN_THUMB =
  "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop";
const QUARTZ_RAW_THUMB =
  "https://images.unsplash.com/photo-1551281044-8af44c4d4a1c?q=80&w=1200&auto=format&fit=crop";
const MINE_THUMB =
  "https://images.unsplash.com/photo-1581092580497-e0d23cbdf1dc?q=80&w=1200&auto=format&fit=crop";

const pool = (data: PoolDraft): PoolDraft => data;

export const POOLS_DATA: Record<SupplierKey, PoolDraft[]> = {
  sterlingAndes: [
    pool({
      name: "Patagonia Silver Vault Bar 1 oz",
      token_symbol: "PATAG1",
      token_name: "Patagonia 1oz Silver",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 50000,
      physical_available: 38500,
      tokens_per_physical_unit: 1,
      total_supply: 50000,
      available_supply: 38500,
      unit_price: 30.5,
      display_unit_label: "1 troy ounce, .999 fine",
      listing_title: "Patagonia 1 oz Silver Vault Bar (.999)",
      listing_body:
        "LBMA-traceable 1 troy-ounce silver bar struck from Patagonia mine output, refined to .999 purity and stored at our Buenos Aires bonded vault. Each token represents one allocated ounce, redeemable at vault or settled in USDC.",
      description: "Vaulted 1 oz silver bar, .999 fine, allocated.",
      thumbnail_url: SILVER_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 4.2,
      volume_mock_usd: 412000,
    }),
    pool({
      name: "Andean Silver Doré 5 kg Brick",
      token_symbol: "ANDD5K",
      token_name: "Andean Doré 5kg",
      asset_class_name: "Silver",
      physical_unit: "kg",
      physical_total: 4000,
      physical_available: 3120,
      tokens_per_physical_unit: 1,
      total_supply: 800,
      available_supply: 624,
      unit_price: 2900,
      display_unit_label: "5 kg silver doré (≈92% Ag)",
      listing_title: "Andean Silver Doré — 5 kg pre-refined brick",
      listing_body:
        "Pre-refined silver doré brick averaging 92% silver content, shipped in tamper-evident 5 kg units from our smelter in Mendoza. Ideal feedstock for refiners and industrial users; assay certificate included.",
      description: "5kg silver doré brick, ~92% Ag, refinery feedstock.",
      thumbnail_url: SILVER_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 1.8,
      volume_mock_usd: 96000,
    }),
    pool({
      name: "Maule Silver Concentrate 60% Ag",
      token_symbol: "MAUSC",
      token_name: "Maule Silver Concentrate",
      asset_class_name: "Silver",
      physical_unit: "kg",
      physical_total: 250000,
      physical_available: 210000,
      tokens_per_physical_unit: 1000,
      total_supply: 250000,
      available_supply: 210000,
      unit_price: 0.62,
      display_unit_label: "1 g concentrate (60% silver)",
      listing_title: "Maule Silver Concentrate — 60% Ag flotation product",
      listing_body:
        "Flotation concentrate from the Maule district averaging 60% silver, with payable copper and lead by-products. Sold in 25-tonne lots; fractional tokenization down to the gram for retail exposure.",
      description: "60% Ag flotation concentrate from Maule district.",
      thumbnail_url: MINE_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -1.2,
      volume_mock_usd: 38000,
    }),
    pool({
      name: "Sterling Mint Series 100 oz Bar",
      token_symbol: "STM100",
      token_name: "Sterling Mint 100oz",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 120000,
      physical_available: 92000,
      tokens_per_physical_unit: 100,
      total_supply: 1200,
      available_supply: 920,
      unit_price: 3050,
      display_unit_label: "100 troy ounces, .999 fine",
      listing_title: "Sterling Mint 100 oz Investment Bar (.999)",
      listing_body:
        "Heavy 100 oz cast bar struck under our Sterling Mint hallmark, ideal for institutional balance-sheet allocations. Bars are stored in segregated, audited bullion storage with insured chain-of-custody.",
      description: "100oz vaulted silver investment bar, .999.",
      thumbnail_url: SILVER_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 5.6,
      volume_mock_usd: 1500000,
    }),
    pool({
      name: "Salar de Uyuni Silver Coin .999",
      token_symbol: "UYUSC1",
      token_name: "Uyuni Silver Coin",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 30000,
      physical_available: 21800,
      tokens_per_physical_unit: 1,
      total_supply: 30000,
      available_supply: 21800,
      unit_price: 42,
      display_unit_label: "1 troy ounce numismatic coin",
      listing_title: "Salar de Uyuni 1 oz Numismatic Silver Coin",
      listing_body:
        "Limited 1 oz numismatic silver coin minted in collaboration with the Bolivian Mint. Includes a numismatic premium reflecting collectible scarcity and certified packaging.",
      description: "Limited numismatic 1oz silver coin.",
      thumbnail_url: SILVER_COIN_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 7.4,
      volume_mock_usd: 280000,
    }),
    pool({
      name: "Mendoza Vault Silver 1 kg",
      token_symbol: "MEND1K",
      token_name: "Mendoza 1kg Silver",
      asset_class_name: "Silver",
      physical_unit: "kg",
      physical_total: 4000,
      physical_available: 3550,
      tokens_per_physical_unit: 1,
      total_supply: 4000,
      available_supply: 3550,
      unit_price: 965,
      display_unit_label: "1 kg .999 silver bar",
      listing_title: "Mendoza Vault — 1 kg .999 Silver Bar",
      listing_body:
        "Cast 1 kg silver bar in .999 purity with serialized assay; held in our Mendoza vault under independent audit.",
      description: "1kg .999 silver bar, vaulted.",
      thumbnail_url: SILVER_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 3.1,
      volume_mock_usd: 410000,
    }),
    pool({
      name: "Cordillera Silver Granules .999",
      token_symbol: "CORDG",
      token_name: "Cordillera Granules",
      asset_class_name: "Silver",
      physical_unit: "gram",
      physical_total: 180000,
      physical_available: 142000,
      tokens_per_physical_unit: 1,
      total_supply: 180000,
      available_supply: 142000,
      unit_price: 0.96,
      display_unit_label: "1 gram .999 fine granules",
      listing_title: "Cordillera Silver Granules — refinery-ready .999",
      listing_body:
        "Free-flowing .999 silver granules packaged in 1 kg flasks; the standard input for jewellers, dental labs and electronics manufacturing.",
      description: ".999 silver granules for industrial use.",
      thumbnail_url: SILVER_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 2.0,
      volume_mock_usd: 64000,
    }),
    pool({
      name: "Atacama Silver Industrial Grade",
      token_symbol: "ATAIN",
      token_name: "Atacama Industrial Ag",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 60000,
      physical_available: 47000,
      tokens_per_physical_unit: 1,
      total_supply: 60000,
      available_supply: 47000,
      unit_price: 28,
      display_unit_label: "1 troy ounce industrial silver",
      listing_title: "Atacama Industrial-Grade Silver — bulk lot",
      listing_body:
        "Industrial-grade silver, .995 fine, priced below numismatic premium. Sold in 5 000 oz lots to OEM buyers and tokenized for retail fractional access.",
      description: ".995 industrial silver, bulk discount.",
      thumbnail_url: SILVER_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -0.4,
      volume_mock_usd: 120000,
    }),
    pool({
      name: "Pampa Silver Investment Bar 10 oz",
      token_symbol: "PAMPS10",
      token_name: "Pampa 10oz Silver",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 85000,
      physical_available: 64000,
      tokens_per_physical_unit: 10,
      total_supply: 8500,
      available_supply: 6400,
      unit_price: 305,
      display_unit_label: "10 troy ounces, .999 fine",
      listing_title: "Pampa 10 oz Silver Investment Bar (.999)",
      listing_body:
        "Mid-size 10 oz cast bar, popular among first-time silver allocators. Sealed in tamper-evident assay cards.",
      description: "10oz silver bar, .999, assay-sealed.",
      thumbnail_url: SILVER_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 4.0,
      volume_mock_usd: 540000,
    }),
    pool({
      name: "Calchaquí Silver Trade Unit 5 oz",
      token_symbol: "CALCS5",
      token_name: "Calchaquí 5oz Silver",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 60000,
      physical_available: 51000,
      tokens_per_physical_unit: 5,
      total_supply: 12000,
      available_supply: 10200,
      unit_price: 152,
      display_unit_label: "5 troy ounces, .999 fine",
      listing_title: "Calchaquí 5 oz Silver Trade Unit",
      listing_body:
        "Compact 5 oz unit struck in our Calchaquí mint. Assayed and serialized; ideal for retail flow and gifting markets.",
      description: "5oz .999 silver trade unit.",
      thumbnail_url: SILVER_COIN_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 2.6,
      volume_mock_usd: 88000,
    }),
  ],

  aurumContinental: [
    pool({
      name: "Sahel Gold Cast Bar 100 g .9999",
      token_symbol: "SAHEL100",
      token_name: "Sahel 100g Gold",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 60000,
      physical_available: 41200,
      tokens_per_physical_unit: 100,
      total_supply: 600,
      available_supply: 412,
      unit_price: 7720,
      display_unit_label: "100 g cast bar, .9999 fine",
      listing_title: "Sahel 100 g Cast Gold Bar (.9999) — LBMA chain",
      listing_body:
        "Cast 100 g gold bar refined from Sahel-region doré, .9999 purity with full LBMA-aligned chain-of-custody documentation. Stored in our London sub-custodian vault.",
      description: "100g .9999 cast gold bar, LBMA-traceable.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 6.4,
      volume_mock_usd: 1850000,
    }),
    pool({
      name: "Volta Gold Doré 250 g",
      token_symbol: "VOLTD250",
      token_name: "Volta Doré 250g",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 100000,
      physical_available: 78000,
      tokens_per_physical_unit: 250,
      total_supply: 400,
      available_supply: 312,
      unit_price: 15250,
      display_unit_label: "250 g doré (≈80% Au)",
      listing_title: "Volta Pre-Refined Doré 250 g",
      listing_body:
        "Pre-refined doré bar averaging 80% gold and 18% silver, shipped from our Ghanaian smelter for refiners and bullion banks.",
      description: "250g pre-refined doré (~80% Au).",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 2.1,
      volume_mock_usd: 660000,
    }),
    pool({
      name: "Ashanti Gold Granule 1 g .9999",
      token_symbol: "ASHG1",
      token_name: "Ashanti 1g Gold",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 250000,
      physical_available: 198000,
      tokens_per_physical_unit: 1,
      total_supply: 250000,
      available_supply: 198000,
      unit_price: 77.2,
      display_unit_label: "1 g .9999 fine granule",
      listing_title: "Ashanti 1 g Gold Granule (.9999)",
      listing_body:
        "1 g gold granule refined from Ashanti basin output, .9999 purity. The smallest fully-allocated unit we sell — perfect for fractional buyers.",
      description: "1g .9999 gold granule, fully allocated.",
      thumbnail_url: GOLD_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 5.0,
      volume_mock_usd: 320000,
    }),
    pool({
      name: "Ghana Mint 1 oz Sovereign Coin",
      token_symbol: "GHANA1",
      token_name: "Ghana Sovereign 1oz",
      asset_class_name: "Gold",
      physical_unit: "troy_ounce",
      physical_total: 5500,
      physical_available: 4100,
      tokens_per_physical_unit: 1,
      total_supply: 5500,
      available_supply: 4100,
      unit_price: 2475,
      display_unit_label: "1 oz minted coin .9999",
      listing_title: "Ghana Mint 1 oz Sovereign Coin (.9999)",
      listing_body:
        "Officially minted 1 oz gold coin issued in collaboration with the Ghana Precious Minerals Marketing Company; numismatic premium over spot.",
      description: "1oz .9999 minted gold coin.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 8.1,
      volume_mock_usd: 540000,
    }),
    pool({
      name: "Niger Delta Gold Bar 250 g",
      token_symbol: "NIGER250",
      token_name: "Niger Delta 250g",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 50000,
      physical_available: 32000,
      tokens_per_physical_unit: 250,
      total_supply: 200,
      available_supply: 128,
      unit_price: 19300,
      display_unit_label: "250 g cast bar, .9999",
      listing_title: "Niger Delta 250 g Cast Gold Bar",
      listing_body:
        "Heavier institutional unit favoured by treasury allocators; cast in our Bamako refinery and stored under audited custody.",
      description: "250g .9999 cast gold bar.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 6.0,
      volume_mock_usd: 1450000,
    }),
    pool({
      name: "Aurum Vault 1 kg Gold",
      token_symbol: "AURVK1",
      token_name: "Aurum Vault 1kg",
      asset_class_name: "Gold",
      physical_unit: "kg",
      physical_total: 80,
      physical_available: 51,
      tokens_per_physical_unit: 1,
      total_supply: 80,
      available_supply: 51,
      unit_price: 77200,
      display_unit_label: "1 kg gold bar, .9999",
      listing_title: "Aurum Vault — 1 kg Gold Bar (.9999)",
      listing_body:
        "Top-tier 1 kg cast bar — the standard wholesale unit for central-bank-style allocations. Vaulted in London with daily audit.",
      description: "1kg .9999 vaulted gold bar.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 7.7,
      volume_mock_usd: 2400000,
    }),
    pool({
      name: "Cape Coast Gold Ingot 50 g",
      token_symbol: "CAPE50",
      token_name: "Cape Coast 50g",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 60000,
      physical_available: 44000,
      tokens_per_physical_unit: 50,
      total_supply: 1200,
      available_supply: 880,
      unit_price: 3860,
      display_unit_label: "50 g cast ingot, .9999",
      listing_title: "Cape Coast 50 g Cast Gold Ingot",
      listing_body:
        "Mid-size 50 g cast ingot, frequently chosen by family offices in West Africa. Comes with serialized assay and tamper-evident packaging.",
      description: "50g .9999 cast gold ingot.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 3.4,
      volume_mock_usd: 920000,
    }),
    pool({
      name: "Mali Gold Sponge 22 K",
      token_symbol: "MALI22",
      token_name: "Mali Sponge 22K",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 18000,
      physical_available: 13800,
      tokens_per_physical_unit: 1,
      total_supply: 18000,
      available_supply: 13800,
      unit_price: 70.8,
      display_unit_label: "1 g sponge, .9167 fine",
      listing_title: "Mali Gold Sponge — 22 K artisanal source",
      listing_body:
        "Sponge gold sourced from cooperative artisanal mines in southern Mali; refined to 22 K (.9167) and audited for ESG compliance.",
      description: "22K artisanal gold sponge, ESG-traced.",
      thumbnail_url: GOLD_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 1.5,
      volume_mock_usd: 78000,
    }),
    pool({
      name: "Continental Gold Wafer 5 g",
      token_symbol: "CONT5",
      token_name: "Continental Wafer 5g",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 110000,
      physical_available: 89000,
      tokens_per_physical_unit: 5,
      total_supply: 22000,
      available_supply: 17800,
      unit_price: 386,
      display_unit_label: "5 g minted wafer, .9999",
      listing_title: "Continental 5 g Minted Gold Wafer (.9999)",
      listing_body:
        "Thin minted wafer, sealed in CertiCard. The most popular retail entry product across the African corridor.",
      description: "5g .9999 minted gold wafer.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 4.3,
      volume_mock_usd: 215000,
    }),
    pool({
      name: "Saharan Gold Dust 1 g .995",
      token_symbol: "SAHAR1",
      token_name: "Saharan Dust 1g",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 60000,
      physical_available: 49000,
      tokens_per_physical_unit: 1,
      total_supply: 60000,
      available_supply: 49000,
      unit_price: 76.85,
      display_unit_label: "1 g placer dust, .995",
      listing_title: "Saharan Placer Gold Dust — 1 g unit",
      listing_body:
        "Placer dust panned from seasonal rivers across the Sahel and refined to .995. Fractional, low-friction exposure for retail buyers.",
      description: ".995 placer gold dust.",
      thumbnail_url: GOLD_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 0.8,
      volume_mock_usd: 96000,
    }),
  ],

  lithionPacific: [
    pool({
      name: "Salar de Atacama Lithium Carbonate Battery Grade",
      token_symbol: "SALCB",
      token_name: "Atacama Li2CO3 BG",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 25000,
      physical_available: 18900,
      tokens_per_physical_unit: 1,
      total_supply: 25000,
      available_supply: 18900,
      unit_price: 19.0,
      display_unit_label: "1 kg Li₂CO₃ ≥99.5%",
      listing_title: "Atacama Battery-Grade Lithium Carbonate (≥99.5%)",
      listing_body:
        "Battery-grade Li₂CO₃ produced from our Atacama brine evaporation ponds; meets specification for cathode precursor manufacturers.",
      description: "Battery-grade Li₂CO₃, ≥99.5%.",
      thumbnail_url: LITHIUM_BRINE_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -2.1,
      volume_mock_usd: 410000,
    }),
    pool({
      name: "Pilbara Spodumene Concentrate 6% Li₂O",
      token_symbol: "PILSP6",
      token_name: "Pilbara SC6",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 800000,
      physical_available: 612000,
      tokens_per_physical_unit: 1,
      total_supply: 800000,
      available_supply: 612000,
      unit_price: 1.1,
      display_unit_label: "1 kg SC6 concentrate",
      listing_title: "Pilbara Spodumene Concentrate (6.0% Li₂O)",
      listing_body:
        "Tier-1 SC6 spodumene concentrate from our Pilbara hard-rock operation. Sold FOB Port Hedland in 25 kt shipments; tokenized down to the kg.",
      description: "6.0% Li₂O spodumene concentrate.",
      thumbnail_url: LITHIUM_PLANT_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -1.0,
      volume_mock_usd: 880000,
    }),
    pool({
      name: "Ganfeng Lithium Hydroxide BG",
      token_symbol: "GANFLH",
      token_name: "Ganfeng LiOH BG",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 15000,
      physical_available: 9800,
      tokens_per_physical_unit: 1,
      total_supply: 15000,
      available_supply: 9800,
      unit_price: 24.0,
      display_unit_label: "1 kg LiOH·H₂O ≥99.5%",
      listing_title: "Battery-Grade Lithium Hydroxide (LiOH·H₂O)",
      listing_body:
        "Coarse battery-grade lithium hydroxide monohydrate, ≥99.5% purity. Specified for high-nickel cathode chemistries.",
      description: "Battery-grade LiOH·H₂O, ≥99.5%.",
      thumbnail_url: LITHIUM_PLANT_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 1.3,
      volume_mock_usd: 360000,
    }),
    pool({
      name: "Greenbushes Premium Spodumene",
      token_symbol: "GREEN6",
      token_name: "Greenbushes Premium",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 600000,
      physical_available: 482000,
      tokens_per_physical_unit: 1,
      total_supply: 600000,
      available_supply: 482000,
      unit_price: 1.18,
      display_unit_label: "1 kg premium SC6.5",
      listing_title: "Greenbushes Premium Spodumene (6.5% Li₂O)",
      listing_body:
        "Top-grade SC6.5 spodumene with low iron and mica contamination. Delivered ex-stockpile at Bunbury terminal.",
      description: "Premium SC6.5 spodumene concentrate.",
      thumbnail_url: LITHIUM_PLANT_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 0.4,
      volume_mock_usd: 720000,
    }),
    pool({
      name: "Olaroz Brine Lithium LCE",
      token_symbol: "OLARO",
      token_name: "Olaroz LCE",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 40000,
      physical_available: 31200,
      tokens_per_physical_unit: 1,
      total_supply: 40000,
      available_supply: 31200,
      unit_price: 5.4,
      display_unit_label: "1 kg LCE pre-refining",
      listing_title: "Olaroz Brine Lithium — LCE feedstock",
      listing_body:
        "Lithium-carbonate-equivalent (LCE) feedstock from the Olaroz brine project; intended for downstream conversion plants seeking long-term volume.",
      description: "Pre-refining LCE feedstock from Olaroz.",
      thumbnail_url: LITHIUM_BRINE_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -0.7,
      volume_mock_usd: 215000,
    }),
    pool({
      name: "Wodgina Spodumene Tier-1",
      token_symbol: "WODGSP",
      token_name: "Wodgina Tier-1",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 750000,
      physical_available: 580000,
      tokens_per_physical_unit: 1,
      total_supply: 750000,
      available_supply: 580000,
      unit_price: 1.05,
      display_unit_label: "1 kg SC6 concentrate",
      listing_title: "Wodgina Tier-1 Spodumene (SC6)",
      listing_body:
        "Long-life Tier-1 spodumene from the Wodgina mine; well-known offtake reference for Asian converters.",
      description: "SC6 Tier-1 spodumene concentrate.",
      thumbnail_url: LITHIUM_PLANT_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -1.6,
      volume_mock_usd: 690000,
    }),
    pool({
      name: "Mt Cattlin Tantalum-Lithium Bundle",
      token_symbol: "MTCAT",
      token_name: "Cattlin Ta-Li",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 200000,
      physical_available: 158000,
      tokens_per_physical_unit: 1,
      total_supply: 200000,
      available_supply: 158000,
      unit_price: 1.35,
      display_unit_label: "1 kg combined Ta-Li conc.",
      listing_title: "Mt Cattlin Tantalum-Lithium Concentrate Bundle",
      listing_body:
        "Combined spodumene + tantalite concentrate stream offering exposure to two strategic minerals from a single mine site.",
      description: "Spodumene + tantalite combined stream.",
      thumbnail_url: MINE_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 2.4,
      volume_mock_usd: 145000,
    }),
    pool({
      name: "Sonora Lithium Clay Resource",
      token_symbol: "SONOLC",
      token_name: "Sonora Clay LCE",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 90000,
      physical_available: 71500,
      tokens_per_physical_unit: 1,
      total_supply: 90000,
      available_supply: 71500,
      unit_price: 3.2,
      display_unit_label: "1 kg LCE clay-derived",
      listing_title: "Sonora Lithium Clay — LCE pilot output",
      listing_body:
        "Clay-derived lithium pilot project in Sonora, Mexico; tokenized exposure to next-generation extraction methods.",
      description: "Clay-derived LCE, pilot project.",
      thumbnail_url: MINE_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 11.2,
      volume_mock_usd: 130000,
    }),
    pool({
      name: "Pacific Recycled Lithium Carbonate",
      token_symbol: "PACRLC",
      token_name: "Pacific Recycled Li₂CO₃",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 30000,
      physical_available: 25500,
      tokens_per_physical_unit: 1,
      total_supply: 30000,
      available_supply: 25500,
      unit_price: 14.8,
      display_unit_label: "1 kg recycled Li₂CO₃",
      listing_title: "Pacific Recycled Lithium Carbonate",
      listing_body:
        "Lithium carbonate recovered from end-of-life EV battery black mass; meets cell-grade specification at a discount to virgin material.",
      description: "Recycled cell-grade Li₂CO₃.",
      thumbnail_url: LITHIUM_PLANT_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 6.9,
      volume_mock_usd: 280000,
    }),
    pool({
      name: "Lithium Phosphate Industrial Grade",
      token_symbol: "LIPIG",
      token_name: "Industrial Li₃PO₄",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 50000,
      physical_available: 43000,
      tokens_per_physical_unit: 1,
      total_supply: 50000,
      available_supply: 43000,
      unit_price: 9.4,
      display_unit_label: "1 kg Li₃PO₄ industrial",
      listing_title: "Industrial-Grade Lithium Phosphate (Li₃PO₄)",
      listing_body:
        "Lithium phosphate intermediate for LFP cathode precursor lines; bulk packed in 25 kg drums.",
      description: "Industrial-grade Li₃PO₄.",
      thumbnail_url: LITHIUM_PLANT_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 0.2,
      volume_mock_usd: 168000,
    }),
  ],

  crystallineQuartz: [
    pool({
      name: "Brazilian HPQ 99.999% Lascas",
      token_symbol: "BRHPQ5",
      token_name: "Brazilian HPQ 5N",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 60000,
      physical_available: 47000,
      tokens_per_physical_unit: 1,
      total_supply: 60000,
      available_supply: 47000,
      unit_price: 4.8,
      display_unit_label: "1 kg HPQ 5N lascas",
      listing_title: "Brazilian HPQ 5N Lascas — semi-grade input",
      listing_body:
        "5N (99.999%) high-purity quartz lascas from our Diamantina vein, the standard feedstock for fused silica crucibles used in mono-crystalline silicon growth.",
      description: "5N HPQ lascas, semi-grade.",
      thumbnail_url: QUARTZ_CRYSTAL_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 9.5,
      volume_mock_usd: 380000,
    }),
    pool({
      name: "Madagascar Optical Quartz Crystal",
      token_symbol: "MADOQC",
      token_name: "Madagascar Optical Qz",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 8000,
      physical_available: 5800,
      tokens_per_physical_unit: 1,
      total_supply: 8000,
      available_supply: 5800,
      unit_price: 25.0,
      display_unit_label: "1 kg optical-grade crystal",
      listing_title: "Madagascar Optical-Grade Quartz Crystal",
      listing_body:
        "Hand-selected optical-grade crystals from Madagascar; used for prisms, oscillators and laser-grade fused silica.",
      description: "Optical-grade quartz crystal, hand-selected.",
      thumbnail_url: QUARTZ_CRYSTAL_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 4.4,
      volume_mock_usd: 92000,
    }),
    pool({
      name: "Spruce Pine Lump Quartz Premium",
      token_symbol: "SPRPLQ",
      token_name: "Spruce Pine HPQ",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 40000,
      physical_available: 32500,
      tokens_per_physical_unit: 1,
      total_supply: 40000,
      available_supply: 32500,
      unit_price: 5.2,
      display_unit_label: "1 kg lump 4N+ HPQ",
      listing_title: "Spruce Pine Lump Quartz — premium 4N+",
      listing_body:
        "Lump quartz from a Spruce Pine sub-supply contract — the iconic semiconductor-industry material. Tokenized for retail exposure to a tightly controlled stream.",
      description: "Spruce Pine lump quartz, premium grade.",
      thumbnail_url: QUARTZ_VEIN_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 11.8,
      volume_mock_usd: 195000,
    }),
    pool({
      name: "Industrial Foundry Quartz Sand",
      token_symbol: "INDFQS",
      token_name: "Industrial Quartz Sand",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 2500000,
      physical_available: 2080000,
      tokens_per_physical_unit: 1,
      total_supply: 2500000,
      available_supply: 2080000,
      unit_price: 0.12,
      display_unit_label: "1 kg silica sand",
      listing_title: "Industrial Foundry Quartz Sand",
      listing_body:
        "Washed and graded foundry-grade silica sand, sold by the bulk lot to glass, foundry and concrete customers.",
      description: "Foundry-grade silica sand, bulk.",
      thumbnail_url: QUARTZ_RAW_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -0.2,
      volume_mock_usd: 110000,
    }),
    pool({
      name: "Jacobina Quartz Pebble",
      token_symbol: "JACQPB",
      token_name: "Jacobina Pebble",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 350000,
      physical_available: 298000,
      tokens_per_physical_unit: 1,
      total_supply: 350000,
      available_supply: 298000,
      unit_price: 0.95,
      display_unit_label: "1 kg construction pebble",
      listing_title: "Jacobina Quartz Pebble — construction grade",
      listing_body:
        "Rounded quartz pebble from Jacobina river deposits; used in landscaping, water filtration and decorative aggregates.",
      description: "Construction-grade quartz pebble.",
      thumbnail_url: QUARTZ_RAW_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 0.6,
      volume_mock_usd: 84000,
    }),
    pool({
      name: "Ouro Preto Crystal Cluster Specimen",
      token_symbol: "OURPCC",
      token_name: "Ouro Preto Cluster",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 1500,
      physical_available: 980,
      tokens_per_physical_unit: 1,
      total_supply: 1500,
      available_supply: 980,
      unit_price: 80.0,
      display_unit_label: "1 kg specimen-grade cluster",
      listing_title: "Ouro Preto Quartz Crystal Cluster — collector grade",
      listing_body:
        "Hand-curated collector clusters from the Ouro Preto district. Each lot is photographed and authenticated before tokenization.",
      description: "Collector-grade quartz cluster.",
      thumbnail_url: QUARTZ_CRYSTAL_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 6.2,
      volume_mock_usd: 78000,
    }),
    pool({
      name: "Tabular Quartz Plate Optical",
      token_symbol: "TABQPO",
      token_name: "Tabular Optical Plate",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 6000,
      physical_available: 4400,
      tokens_per_physical_unit: 1,
      total_supply: 6000,
      available_supply: 4400,
      unit_price: 32.0,
      display_unit_label: "1 kg sliced tabular plate",
      listing_title: "Tabular Quartz Plate — optical-cut blanks",
      listing_body:
        "Pre-cut tabular quartz plates ready for optical polishing; used in oscillators, frequency standards and laser optics.",
      description: "Pre-cut optical quartz plates.",
      thumbnail_url: QUARTZ_CRYSTAL_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 3.0,
      volume_mock_usd: 88000,
    }),
    pool({
      name: "Smoky Quartz Specimen Lot",
      token_symbol: "SMKQSL",
      token_name: "Smoky Quartz Lot",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 4500,
      physical_available: 3700,
      tokens_per_physical_unit: 1,
      total_supply: 4500,
      available_supply: 3700,
      unit_price: 48.0,
      display_unit_label: "1 kg smoky specimens",
      listing_title: "Smoky Quartz Specimen Lot — collector mix",
      listing_body:
        "Mixed lot of smoky quartz specimens curated from Brazilian and Madagascan sources. Photo-documented per piece.",
      description: "Collector smoky quartz specimens.",
      thumbnail_url: QUARTZ_CRYSTAL_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 2.4,
      volume_mock_usd: 56000,
    }),
    pool({
      name: "High-Purity Quartz Powder Semi Grade",
      token_symbol: "HPQPSG",
      token_name: "HPQ Powder 4N",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 80000,
      physical_available: 64000,
      tokens_per_physical_unit: 1,
      total_supply: 80000,
      available_supply: 64000,
      unit_price: 4.2,
      display_unit_label: "1 kg HPQ 4N powder",
      listing_title: "HPQ Powder 4N — semi-grade flowable",
      listing_body:
        "Dry-milled 4N high-purity quartz powder, free-flowing. Standard input for fused-silica crucible coatings.",
      description: "4N HPQ powder, free-flowing.",
      thumbnail_url: QUARTZ_RAW_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 7.0,
      volume_mock_usd: 245000,
    }),
    pool({
      name: "Rose Quartz Bulk Ton",
      token_symbol: "ROSQBT",
      token_name: "Rose Quartz Ton",
      asset_class_name: "Quartz",
      physical_unit: "ton",
      physical_total: 1200,
      physical_available: 940,
      tokens_per_physical_unit: 1,
      total_supply: 1200,
      available_supply: 940,
      unit_price: 640,
      display_unit_label: "1 metric ton bulk lot",
      listing_title: "Rose Quartz — bulk decorative ton",
      listing_body:
        "Decorative-grade rose quartz sold by the metric ton from our Bahia quarry; popular with lapidaries and wholesale gem cutters.",
      description: "Decorative-grade rose quartz, bulk.",
      thumbnail_url: QUARTZ_RAW_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 1.6,
      volume_mock_usd: 64000,
    }),
  ],

  polarisNorthern: [
    pool({
      name: "Yukon Gold Placer 1 oz",
      token_symbol: "YUKGP1",
      token_name: "Yukon Placer 1oz",
      asset_class_name: "Gold",
      physical_unit: "troy_ounce",
      physical_total: 4000,
      physical_available: 2900,
      tokens_per_physical_unit: 1,
      total_supply: 4000,
      available_supply: 2900,
      unit_price: 2460,
      display_unit_label: "1 oz placer gold .9999",
      listing_title: "Yukon Placer Gold — 1 oz refined",
      listing_body:
        "Placer gold dredged from our Klondike-area lease, refined to .9999 and minted into 1 oz rounds. Limited annual production.",
      description: "Refined Yukon placer gold, 1oz.",
      thumbnail_url: GOLD_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 5.9,
      volume_mock_usd: 245000,
    }),
    pool({
      name: "Athabasca Silver Concentrate 50%",
      token_symbol: "ATHASC",
      token_name: "Athabasca Ag Conc",
      asset_class_name: "Silver",
      physical_unit: "kg",
      physical_total: 200000,
      physical_available: 170000,
      tokens_per_physical_unit: 1000,
      total_supply: 200000,
      available_supply: 170000,
      unit_price: 0.48,
      display_unit_label: "1 g concentrate, 50% Ag",
      listing_title: "Athabasca Silver Concentrate (50% Ag)",
      listing_body:
        "Lead-silver flotation concentrate from our Athabasca basin operations. Smelter-ready in 25 t shipments.",
      description: "50% Ag flotation concentrate.",
      thumbnail_url: MINE_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: -0.9,
      volume_mock_usd: 42000,
    }),
    pool({
      name: "Manitoba Quartz Vein Specimen",
      token_symbol: "MANQVS",
      token_name: "Manitoba Vein Qz",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 3500,
      physical_available: 2600,
      tokens_per_physical_unit: 1,
      total_supply: 3500,
      available_supply: 2600,
      unit_price: 58.0,
      display_unit_label: "1 kg vein-quartz specimen",
      listing_title: "Manitoba Vein Quartz — gold-bearing specimen",
      listing_body:
        "Vein-quartz specimens carrying visible micro-gold; sold to collectors and educational institutions.",
      description: "Gold-bearing quartz vein specimen.",
      thumbnail_url: QUARTZ_VEIN_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 2.7,
      volume_mock_usd: 32000,
    }),
    pool({
      name: "Boreal Gold Bullion 50 g",
      token_symbol: "BORGB50",
      token_name: "Boreal 50g Gold",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 40000,
      physical_available: 31200,
      tokens_per_physical_unit: 50,
      total_supply: 800,
      available_supply: 624,
      unit_price: 3860,
      display_unit_label: "50 g cast gold bar .9999",
      listing_title: "Boreal 50 g Cast Gold Bar (.9999)",
      listing_body:
        "Cast 50 g bar refined from our Yukon doré stream; assayed and serialized.",
      description: "50g .9999 Yukon-refined gold bar.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 4.6,
      volume_mock_usd: 410000,
    }),
    pool({
      name: "Hudson Bay Silver Bar 100 oz",
      token_symbol: "HUDSB100",
      token_name: "Hudson Bay 100oz",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 150000,
      physical_available: 118000,
      tokens_per_physical_unit: 100,
      total_supply: 1500,
      available_supply: 1180,
      unit_price: 3025,
      display_unit_label: "100 oz silver bar .999",
      listing_title: "Hudson Bay 100 oz Silver Bar (.999)",
      listing_body:
        "Heavy 100 oz silver bar struck from Athabasca-derived silver and refined to .999. Preferred by Canadian RRSP/RESP allocators.",
      description: "100oz .999 silver bar.",
      thumbnail_url: SILVER_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 3.2,
      volume_mock_usd: 720000,
    }),
    pool({
      name: "Polar Gold Dust .995",
      token_symbol: "POLGD",
      token_name: "Polar Dust",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 28000,
      physical_available: 22500,
      tokens_per_physical_unit: 1,
      total_supply: 28000,
      available_supply: 22500,
      unit_price: 76.85,
      display_unit_label: "1 g placer dust .995",
      listing_title: "Polar Placer Gold Dust — 1 g unit",
      listing_body:
        "Sub-Arctic placer gold dust refined to .995 and shipped from our Whitehorse facility.",
      description: ".995 polar placer gold dust.",
      thumbnail_url: GOLD_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 1.0,
      volume_mock_usd: 48000,
    }),
    pool({
      name: "Northern Lithium Brine Pilot LCE",
      token_symbol: "NORLBP",
      token_name: "Northern Brine LCE",
      asset_class_name: "Lithium",
      physical_unit: "kg",
      physical_total: 18000,
      physical_available: 14400,
      tokens_per_physical_unit: 1,
      total_supply: 18000,
      available_supply: 14400,
      unit_price: 4.8,
      display_unit_label: "1 kg LCE pilot",
      listing_title: "Northern Lithium Brine Pilot — LCE",
      listing_body:
        "Pilot-stage lithium brine project in Saskatchewan; tokenization gives early-stage exposure to a Canadian on-shore lithium source.",
      description: "Pilot-stage LCE, Saskatchewan brine.",
      thumbnail_url: LITHIUM_BRINE_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 8.5,
      volume_mock_usd: 64000,
    }),
    pool({
      name: "Arctic HPQ 4N Grade",
      token_symbol: "ARCHPQ",
      token_name: "Arctic HPQ 4N",
      asset_class_name: "Quartz",
      physical_unit: "kg",
      physical_total: 22000,
      physical_available: 17500,
      tokens_per_physical_unit: 1,
      total_supply: 22000,
      available_supply: 17500,
      unit_price: 4.5,
      display_unit_label: "1 kg HPQ 4N",
      listing_title: "Arctic HPQ 4N — Canadian HPQ alternative",
      listing_body:
        "4N high-purity quartz from our Manitoba vein, positioned as a domestic North-American alternative to Spruce Pine HPQ.",
      description: "Canadian 4N HPQ.",
      thumbnail_url: QUARTZ_CRYSTAL_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 6.8,
      volume_mock_usd: 88000,
    }),
    pool({
      name: "Ontario Silver Round 1 oz Limited",
      token_symbol: "ONTSR1",
      token_name: "Ontario Round 1oz",
      asset_class_name: "Silver",
      physical_unit: "troy_ounce",
      physical_total: 18000,
      physical_available: 13800,
      tokens_per_physical_unit: 1,
      total_supply: 18000,
      available_supply: 13800,
      unit_price: 34,
      display_unit_label: "1 oz silver round .999",
      listing_title: "Ontario Limited Silver Round 1 oz (.999)",
      listing_body:
        "Limited-edition 1 oz silver round struck for Polaris Northern's 25th anniversary; numismatic premium over spot.",
      description: "1oz .999 silver limited round.",
      thumbnail_url: SILVER_COIN_THUMB,
      status: "tokenized",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 4.0,
      volume_mock_usd: 120000,
    }),
    pool({
      name: "Saskatchewan Gold Wafer 5 g",
      token_symbol: "SASKGW5",
      token_name: "Saskatchewan 5g",
      asset_class_name: "Gold",
      physical_unit: "gram",
      physical_total: 45000,
      physical_available: 36500,
      tokens_per_physical_unit: 5,
      total_supply: 9000,
      available_supply: 7300,
      unit_price: 386,
      display_unit_label: "5 g minted gold wafer .9999",
      listing_title: "Saskatchewan 5 g Minted Gold Wafer (.9999)",
      listing_body:
        "5 g minted gold wafer with the Saskatchewan provincial hallmark; popular gifting and entry-level investment unit.",
      description: "5g .9999 minted gold wafer.",
      thumbnail_url: GOLD_BAR_THUMB,
      status: "approved",
      blockchain_status: "minted",
      marketplace_listed: true,
      performance_mock_pct: 3.6,
      volume_mock_usd: 175000,
    }),
  ],
};
